In [2]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.numel()

12

In [4]:
X = x.reshape(3,4)

In [5]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
#创建一个全0的张量，形状为（2，3，4）
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn((3,4,))

tensor([[-0.4205, -2.1480,  0.9619, -1.1577],
        [-1.3392,  1.4363, -0.5818,  0.5194],
        [-1.3754, -1.0976, -0.5413,  1.4943]])

In [10]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [14]:
#元组里的元素分别计算
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y , x - y , x * y , x / y , x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
#求幂
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
#张量按行/按列连结（concatenate）
#在元组结尾的元素加逗号没有问题，不会引起报错
X = torch.arange(12,dtype=torch.float).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4,],[4,3,2,1]])
torch.cat((X,Y),dim = 0),torch.cat((X,Y),dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [26]:
#判断元素是否相等
print(X)
print(Y)
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [25]:
#对张量中所有的元素求和，生成一个单元素张量
X.sum()

tensor(66.)

In [30]:
#广播机制——针对形状不同的张量，调用广播机制来对元素进行操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a + b
#结果为大的行+大的列，数值为每个元素进行运算

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [32]:
#索引和切片。第一个元素的索引是0，最后一个元素索引是-1；可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素
print(X)
X[-1]
X[1:3]
#这里有个小tips，如果只在最后一行输入张量名，就只显示最后一行的，如果要同时显示两个张量，在最后一行写X，Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
X = torch.arange(12).reshape((4,3))
print(X)
X[1:3]#索引1到索引3，左包含右不包含

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


tensor([[3, 4, 5],
        [6, 7, 8]])

In [51]:
Y = torch.arange(40).reshape((5,2,4))
Y

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [52]:
Y[1:3]#OK

tensor([[[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [56]:
Y[1,0,3]

tensor(11)

In [85]:
#赋值
X = torch.arange(12).reshape((4,3))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X[1:,1:] = 12
X
#ok

tensor([[ 0,  1,  2],
        [ 3, 12, 12],
        [ 6, 12, 12],
        [ 9, 12, 12]])

In [88]:
X = torch.arange(12).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(Y)
Y = X + Y
id(Y) == before

False

In [109]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
print(Z)
Z[::] = X + Y #[:]和[::]可以使用原来的内存分配
print('id(Z):', id(Z))
print(Z)

id(Z): 2483621859248
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 2483621859248
tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])


In [116]:
#或者使用X += Y也可以利用原来的内存分配
X = torch.arange(12).reshape((3,4)).long()
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]]).long()
before = id(X)
X += Y
id(X) == before
#新版本的torch无法自动执行转换操作,在+可以，在+=不可以

True

In [117]:
X = torch.arange(12).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
before = id(X)
X = Y + X
id(X) == before

False

In [118]:
#深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [119]:
#要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [2]:
import torch
print(torch.__version__) 

2.1.0+cu121


In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [12]:
x = x.reshape(-1,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
torch.zeros((2,3,4,))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
x = torch.ones((2,3,4))
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
torch.randn(3,4)

tensor([[-0.5553,  0.4727,  0.6813,  1.2877],
        [ 0.1992,  0.5225,  0.2488, -2.7110],
        [ 0.4959,  0.2985, -0.6067, -2.1646]])

In [18]:
torch.tensor([[2,3,4,0],[1,2,3,4],[4,3,2,1]])

tensor([[2, 3, 4, 0],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [19]:
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
torch.exp(x)

tensor([[[2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183]],

        [[2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183],
         [2.7183, 2.7183, 2.7183, 2.7183]]])

In [25]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[1,2,3,4],[2,2,3,4],[3,2,3,4]])
torch.cat((X,Y),dim = 0),torch.cat((X,Y),dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  2.,  3.,  4.],
         [ 3.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  3.,  2.,  3.,  4.]]))

In [26]:
X == Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
Y.sum()

tensor(33)

调用广播机制对不同形状的张量进行操作

In [42]:
import numpy as np
trial_count = 16
random_trial = np.random.choice(np.arange(1, trial_count + 1), size=3, replace=False)
print(random_trial)

[ 8  1 10]
